<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-DCJJA81" failures="0" tests="5" name="pk_Assignments.Assignment2" time="5.287" errors="1" timestamp="2023-03-08T14:41:24 IST" skipped="2">
  <testcase classname="pk_Assignments.Assignment2" name="changeOrderStatus" time="0.000">
    <error message="
Method public void pk_Assignments.Assignment2.changeOrderStatus(java.lang.String,java.lang.String) requires a @DataProvider named : Different_Status_Scenario in class assignments.Test_Data" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void pk_Assignments.Assignment2.changeOrderStatus(java.lang.String,java.lang.String) requires a @DataProvider named : Different_Status_Scenario in class assignments.Test_Data
at org.testng.internal.Parameters.findDataProvider(Parameters.java:561)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- changeOrderStatus -->
  <system-out/>
  <testcase classname="pk_Assignments.Assignment2" name="resetOrderStatus" time="0.000">
    <skipped/>
  </testcase> <!-- resetOrderStatus -->
  <system-out/>
  <testcase classname="pk_Assignments.Assignment2" name="logout" time="0.000">
    <skipped/>
  </testcase> <!-- logout -->
  <system-out/>
  <testcase classname="pk_Assignments.Assignment2" name="navigateToSalesOrderPage" time="2.009"/>
  <system-out/>
  <testcase classname="pk_Assignments.Assignment2" name="login" time="3.278"/>
  <system-out/>
</testsuite> <!-- pk_Assignments.Assignment2 -->
